### ISSUE TITLE
Product mode

### ISSUE THREAD

**Issue by obaviet** [grandnode/grandnode2#111]
Hello
I read the description that version 2.0 is headless but in this repository there is only one packaged all-in-one version
The packaged version is great for quick installation and testing. However, to deploy the production model. I'm really confused.
For production deployment I would probably install the backend on a different server than the fontend, even the database in a different place.

**Comment by PatrykPorabik** [comment]
You can run the admin panel on different servers, then frontend on different servers. But it requires technical knowledge.

**Comment by obaviet** [comment]
The problem is that there is no documentation. I do not see it.
When will you release the manual?
