### ISSUE TITLE
General settings not save correctly in multi store scenario

### ISSUE THREAD

**Issue by pourali1982** [grandnode/grandnode2#112]
Hi,
I do some change in admin panel(add user as admin and stuff, add second store, ...). 
Second user who is stuff of a store and have some extra permission (mohsen@gmail.com pass: 111111)  change  setting=>General=>Time zone , default theme and ...
but
first user who is admin (admin@yourstore.com pass: 123)  never see the new configuration.
I tried to repeat the scenario but it is not happened again. I dont know the sequence of operation that I do, so I send you my database backup.

Best regard
[plugins.zip](https://github.com/grandnode/grandnode2/files/7147370/plugins.zip)

**Comment by PatrykPorabik** [comment]
Please add a comment when you figure out how to reproduce the issue in our environment.

**Comment by pourali1982** [comment]
Ok mr. Porabik, I appreciate you for developing your environment
