### ISSUE TITLE
"User not exists or password is wrong" While enabling backend API

### ISSUE THREAD

**Issue by avinashgoud** [grandnode/grandnode2#118]
I have followed exactly as per the documentation.
Using the latest codebase

"Api": {
    "Enabled": true,
    "UseSwagger": true,
    "SecretKey": "F3526D2AE388CF43BBFCED577DE7C", //at least 16 characters
    "ValidateIssuer": false,
    "ValidIssuer": "",
    "ValidateAudience": false,
    "ValidAudience": "",
    "ValidateLifetime": true,
    "ValidateIssuerSigningKey": true,
    "ExpiryInMinutes": 1440,
    //generate system model
    "SystemModel": true
  },  

curl -X 'POST' \
  'http://localhost:16593/Api/Token/Create' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
    "email": "admin@yourstore.com",
    "password": "YWRtaW5hZG1pbg=="
}'

{
  "errors": {
    "": [
      "User not exists or password is wrong"
    ]
  },
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-8fc59a140a3bc94c88e4404b7228aa6c-26ca5b73104abb42-00"
}

**Comment by KrzysztofPajak** [comment]
Fixed https://grandnode.com/boards/topic/5c9b7cfa0a0af1213c09a006/api-loginvalidator-password-does-not-validate
