### ISSUE TITLE
{{Order.PaymentMethod}} always empty in the "OrderPlaced.CustomerNotification" MessageTemplate

### ISSUE THREAD

**Issue by attila-koteles** [grandnode/grandnode2#128]
This becomes a problem when notifying the customer about the recently placed order.  
The issue is caused by an unpopulated WorkContext object, used by the TranslationService.  
This same issue affects the notification towards the shop owner too.

I prepared a #124 pull request with a fix. It can be merged to the 1.0.x branch.

It would be great if this issue could be resolved. This is a very important information for the customer. _(and shop owner)_

**Comment by PatrykPorabik** [comment]
Thanks a lot for contribution.
