### ISSUE TITLE
Import external Language resources won't work

### ISSUE THREAD

**Issue by khaledafify** [grandnode/grandnode2#13]
Hi ,

I'm trying to import Arabic Language Resources , it's appear as a successful operation but nothing was imported

**Comment by PatrykPorabik** [comment]
Hello,

I suppose you are trying to import the Arabic Language Resources from GrandNode v1. In that case, it won't work. GrandNode v2 has a different XML structure, so firstly you would need to modify it. Please look at the default language file and make appropriate changes if you want - https://github.com/grandnode/grandnode2/blob/master/src/Web/Grand.Web/App_Data/Resources/DefaultLanguage.xml
