### ISSUE TITLE
Bugged language change

### ISSUE THREAD

**Issue by norbertmarkiel** [grandnode/grandnode2#132]
After adding any language, the panel becomes buggy, details in the attached photo.
![image](https://user-images.githubusercontent.com/10126507/136380463-53cdf1c2-304e-42ff-bc4e-e498d5889963.png)

**Comment by PatrykPorabik** [comment]
It's not a bug, if you don't add language pack or resource strings you will receive something like that. Those strings you can see, like admin.dashboard.activityoverview, etc. are localizable resource strings. You can add them by Importing language pack in Admin -> Configuration -> Languages, or by adding them manually on Language edition page, in the Resource Strings tab
