### ISSUE TITLE
Error js vue homepage

### ISSUE THREAD

**Issue by music13245678** [grandnode/grandnode2#155]
![error](https://user-images.githubusercontent.com/48851343/139533027-f189387f-3c96-4eee-9b73-22c899d5ee09.png)

I installed the latest for grandnode commit "2a3eca0ee3d7d5a9a49e876870aa972fbd0310c6", after installation opened the homepage to a pure white screen with no display due to js vue error.

**Comment by music13245678** [comment]
![error_detail](https://user-images.githubusercontent.com/48851343/139533153-04546291-18b1-483e-a3f6-c35139a45792.png)
The product detail page also has an error

Commit: search boxes - minor changes
https://github.com/grandnode/grandnode2/commit/2a3eca0ee3d7d5a9a49e876870aa972fbd0310c6

**Comment by PatrykPorabik** [comment]
First of all, press CTRL  F5, maybe something is cached in your browser. If it doesn't help, you will need to install the latest stable version - 1.0.2. It's not recommended to use the master branch because it's a development branch.
