### ISSUE TITLE
Widget slider is showing other stores images

### ISSUE THREAD

**Issue by balureddy003** [grandnode/grandnode2#193]
- When you have two stores in the same instance and add a widget slider to both the stores with limited stores field set to respective store for each slider 
- When you browse each store, it will show all slides add to the widget slider instead of filtering them based on the limited stores field values

**Comment by PatrykPorabik** [comment]
Hi @balureddy003 ,

Did you set the IgnoreStoreLimitations to false in the App_Data/appsettings.json file? https://github.com/grandnode/grandnode2/blob/master/src/Web/Grand.Web/App_Data/appsettings.json#L132

**Comment by balureddy003** [comment]
Yes. It is set to False.

**Comment by PatrykPorabik** [comment]
We will check it. Thanks for reporting

**Comment by balureddy003** [comment]
I raised PR for fixing this issue, please review and approve if you think it is the right to fix.
https://github.com/i-cuboid/grandnode2/commit/3c66b7a2a10520b4395f515ceef56119f2043ccb
