### ISSUE TITLE
Product short description should be conveted to HTML Editor

### ISSUE THREAD

**Issue by balureddy003** [grandnode/grandnode2#199]
- In product management, converting the short description field to HMTL editor like full description will have a lot of advantages for customization of short description field in product view.

Let me know if I can contribute to this change.

![image](https://user-images.githubusercontent.com/7783528/145704935-f2cc8e78-1e36-49dd-aebc-5b707b0db77d.png)

**Comment by KrzysztofPajak** [comment]
@balureddy003 
I don't know if it should be converted to HTML Editor.
We leave it to customization by the customer.

**Comment by balureddy003** [comment]
@KrzysztofPajak  I did convert this to "Editor". It works nicely. Do you see any harm in doing this on the platform?
![image](https://user-images.githubusercontent.com/7783528/145715501-c2f83154-2276-4c40-8122-c2991bc7b499.png)

![image](https://user-images.githubusercontent.com/7783528/145715524-c960b19a-cb93-4efa-a840-cb0d5c5a29f8.png)

**Comment by KrzysztofPajak** [comment]
@balureddy003 Check how it's a look the catalog page.

**Comment by balureddy003** [comment]
@KrzysztofPajak  it really looks good.

![image](https://user-images.githubusercontent.com/7783528/145720344-729c4cff-0ce3-4a92-b4a8-91b38ac8d5bf.png)

**Comment by KrzysztofPajak** [comment]
@balureddy003 Check on the catalog page, on the list of product.

**Comment by balureddy003** [comment]
@KrzysztofPajak it should work, we just need to give a shorter description to fit in that place.
![image](https://user-images.githubusercontent.com/7783528/145745985-325ba470-c19f-4253-adac-787b4a390c06.png)

**Comment by KrzysztofPajak** [comment]
@balureddy003 As you see it's better to leave it for customization
