### ISSUE TITLE
Add support for CosmosDB

### ISSUE THREAD

**Issue by KrzysztofPajak** [grandnode/grandnode2#20]
Add support for CosmosDB

**Comment by ranasch** [comment]
What is the status regarding CosmosDB support? In the setup I can choose "CosmosDB" but it fails. Is CosmosDB supported? With SQL API or Mongo? Any instructions?

**Comment by PatrykPorabik** [comment]
It should be supported. We've tested it a few times. What kind of error did you receive?

**Comment by ranasch** [comment]
Created a new CosmosDB with Mongo API (4.0). Error:
Setup failed: Command create failed: Error=13, Details='Response status code does not indicate success: Forbidden (403); Substatus: 1021; ActivityId: c034cf5b-5189-4a0b-8ef6-ddd43c8762af; Reason: (Message: {"Errors":["Storage quota for 'Collection' exceeded."]} ActivityId: c034cf5b-5189-4a0b-8ef6-ddd43c8762af, Request URI: /apps/48e75550-63c2-456b-8346-30f89779a74b/services/294fe071-1d48-467a-98bc-fdfcc2ffa0dc/partitions/5a1e9355-db8c-4262-aacd-eca007480b86/replicas/132655836081360823p, RequestStats: , SDK: Microsoft.Azure.Documents.Common/2.11.0, Please see CosmosDiagnostics, Windows/10.0.17763 cosmos-netstandard-sdk/3.3.2);.

**Comment by PatrykPorabik** [comment]
Well, it looks like you exceeded the storage quota, I suppose it's something related to the limits on your account.

**Comment by ranasch** [comment]
found the issue: Serverless is not supported...

**Comment by PatrykPorabik** [comment]
Well, it may be a reason. As far as I know, our developers haven't tested it on CosmosDB with consumption-based pricing.
