### ISSUE TITLE
Product pictures with youtube video url's

### ISSUE THREAD

**Issue by balureddy003** [grandnode/grandnode2#201]
- Can we extend product pictures with the option to add youtube video URLs so that they can be shown product gallery

**Comment by KrzysztofPajak** [comment]
Thanks for the suggestion we will consider it to the next version.

**Comment by balureddy003** [comment]
@KrzysztofPajak  what is the timeline for the next version?

**Comment by balureddy003** [comment]
Thanks @KrzysztofPajak
