### ISSUE TITLE
Return JSON in camelCase instead of PascalCase

### ISSUE THREAD

**Issue by yamin8000** [grandnode/grandnode2#213]
How can I config either GrandNode or OData to return JSON in camelCase instead of the current default which is returning in PascalCase?

sample:

```JSON
{
    "Name": "Xiaomi",
    "SeName": "xiaomi",
    "Description": null,
    "BottomDescription": null,
    "BrandLayoutId": "61b57b85892acc894cd7efb9",
    "MetaKeywords": null,
    "MetaDescription": null,
    "MetaTitle": null,
    "PictureId": "61b57b85892acc894cd7f020",
    "PageSize": 6,
    "AllowCustomersToSelectPageSize": true,
    "PageSizeOptions": "6, 3, 9",
    "ShowOnHomePage": false,
    "IncludeInMenu": false,
    "Icon": null,
    "Published": true,
    "ExternalId": null,
    "DisplayOrder": 1,
    "Id": "61b57b85892acc894cd7f01f"
  }
```

**Comment by KrzysztofPajak** [comment]
@yamin8000 
I think it doesn't matter if you send a field i.e. Name with upper case or lower case.

**Comment by yamin8000** [comment]
> @yamin8000 I think it doesn't matter if you send a field i.e. Name with upper case or lower case.

Thank you for your swift response.
Yeah for sending data to the server maybe that doesn't matter but it would be great if API consumer (Client) could receive JSON in the desired format (one way of that is using HTTP headers), many JSON parsers are very strict when it comes to field name cases and consider `Name` or `name` two completely different fields.

**Comment by KrzysztofPajak** [comment]
@yamin8000 
It looks like it's possible, find the file ODataStartup.cs  => Method GetEdmModel:
        private IEdmModel GetEdmModel(ApiConfig apiConfig)
        {
            var builder = new ODataConventionModelBuilder {
                Namespace = Configurations.ODataModelBuilderNamespace,
            };
            //add this line
            builder.EnableLowerCamelCase();
            RegisterDependencies(builder, apiConfig);
            return builder.GetEdmModel();
        }
