### ISSUE TITLE
500 Internal Server Error when using $filter=contains(field,'X')

### ISSUE THREAD

**Issue by yamin8000** [grandnode/grandnode2#215]
I'm using GrandNode2 `1.1.0` with Plesk and I'm using [this ](https://grandnode.com/why-odata-rest-api-is-the-best-for-your-grandnode-online-store)as reference.

When using Brand API with no `$filter` query or if I use a query like `$filter=Name eq 'Xiaomi'` then the response is OK.

`https://otrade.ir/odata/Brand`

![image](https://user-images.githubusercontent.com/5001708/147057699-6cfa5748-c4bd-43c0-ad7d-003b79961a84.png)

However, if I add a filter query like `$filter=contains(Name,'X')`, then HTTP response code is 500 and HTTP response body is like this:
```
IIF((({document}{Name} == null) OrElse False), null, Convert({document}{Name}.Contains("X"), Nullable`1)) is not supported.
```

I want to know what's the root cause of the problem. is it related to MongoDB driver or some other thing?

```batch
curl -X 'GET' 'https://otrade.ir/odata/Brand?$filter=contains(Name,'\''X'\'')' -H 'accept: */*' -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJhNjcwNmE2Yy1jZDE0LTQwNWYtOTdkOC01YWJjYmZhYjljNmIiLCJFbWFpbCI6InlhbWluODAwMEB5YWhvby5jb20iLCJUb2tlbiI6IjE3Yzk5NWU5LTNhZTAtNGU5Mi05ZDIwLTk1MTYwNDUzMmYyOCIsImV4cCI6MTcyNjI4OTg4NX0._CD3jFSsMz1_-eiN2LcK1sAEFY69ZDhRP1DBRuoMRN4'
```

[related to the issue in another project](https://github.com/TradersTeam/grand-node-java-client/issues/28)
@ariantron

**Comment by ariantron** [comment]
I have this problem too!
@KrzysztofPajak 
@PatrykPorabik

**Comment by KrzysztofPajak** [comment]
Your issue is related to the MongoDB driver.
