### ISSUE TITLE
BadImageFormatException: Bad IL format.

### ISSUE THREAD

**Issue by serdarozbilen** [grandnode/grandnode2#216]
When Grand.Web.Admin and Grand.Web.Common projects added to plugin reference throws exception 
_BadImageFormatException: Bad IL format. The format of the file "xxxxxxxx......master\src\Web\Grand.Web\Plugins\bin\libzstd.dll' is invalid._

```
<ProjectReference Include="..\..\Web\Grand.Web.Admin\Grand.Web.Admin.csproj" />
<ProjectReference Include="..\..\Web\Grand.Web.Common\Grand.Web.Common.csproj">
       <Private>false</Private>
</ProjectReference>
```

**Comment by KrzysztofPajak** [comment]
@serdarozbilen 
If you add Grand.Web or Grand.Web.Admin reference please add all references:
 <ItemGroup>
    <ProjectReference Include="..\..\Business\Grand.Business.Authentication\Grand.Business.Authentication.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Catalog\Grand.Business.Catalog.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Checkout\Grand.Business.Checkout.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Cms\Grand.Business.Cms.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Common\Grand.Business.Common.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Customers\Grand.Business.Customers.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Marketing\Grand.Business.Marketing.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Messages\Grand.Business.Messages.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.Storage\Grand.Business.Storage.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Business\Grand.Business.System\Grand.Business.System.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Core\Grand.Domain\Grand.Domain.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Core\Grand.Infrastructure\Grand.Infrastructure.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Core\Grand.SharedKernel\Grand.SharedKernel.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Web\Grand.Web.Common\Grand.Web.Common.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

**Comment by serdarozbilen** [comment]
Oww so sorry.
Thank you so much @KrzysztofPajak
