### ISSUE TITLE
Develop - Migration script to 2.0 is not present

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#217]
On the latest code pull, the source code is upgraded to version 2.0. 
Will we be able to apply any migration on the database having version 1.1 and move to 2.0?

**Comment by KrzysztofPajak** [comment]
@Nikhil13x 
The migration process will be available soon to version 2.0.0 - this is a developing version so it's better don't use it in production. For production please use branch 1.1.X
