### ISSUE TITLE
Edits made in "Code view" of summer note plugin is not saved on clicking save.

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#218]
On the WYSIWYG editor, in Landing pages or Knowledgebase, if you make any content modifications in Code view, its not persisted when clicked on save.
But, before saving, if you turn the "Code View" off, and then click on save, it gets saved.

Either the save button need to be disabled until the code view is turned off, or saving while in the code view need to get saved on clicking save button.
Or atleast, showing a note >> "switch off "Code View" before saving" - might be helpful

**Comment by KrzysztofPajak** [comment]
Please check this https://github.com/summernote/django-summernote/issues/127
