### ISSUE TITLE
Misleading documentation

### ISSUE THREAD

**Issue by mahyar1386** [grandnode/grandnode2#220]
I've been checking frontend web API documentation and I've encountered `http://storeurl/systemname` multiple times, but I can't figure out how to use it and how it works.

for example, how to get product details with a specific Id?

What are the possible values to be replaced with `systemname`?

![image](https://user-images.githubusercontent.com/2510129/147639298-5fcb8952-ffde-4dcd-bdf4-4de86446befc.png)

![image](https://user-images.githubusercontent.com/2510129/147639308-116d02b6-5658-49b7-be10-5a642700972d.png)

**Comment by KrzysztofPajak** [comment]
If you need help with some features please send them on our board https://grandnode.com/boards
