### ISSUE TITLE
Improvement: Ability to have custom URL for content pages is missing.

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#221]
Whenever a content page is created, the system auto generates a seo name/slug/URL for the page. 
The user may need a provision to provide the custom URL to the page (the relative path).

This is useful when an existing e-commerce company want to migrate to grandnode and they have already done a lot of marketing based on their current URL structure.

Can this be contributed?

**Comment by KrzysztofPajak** [comment]
You can edit field - "Search engine friendly page name" 
![image](https://user-images.githubusercontent.com/16772986/147754045-7e3c2bf2-fc1a-49f3-a1fb-32d1d0a703cf.png)

**Comment by KrzysztofPajak** [comment]
If you need help with some features please send them on our board https://grandnode.com/boards
