### ISSUE TITLE
In courses --> lessons, can we have a provision to embed YouTube video URLS?

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#228]
Since the Youtube videos are not getting downloaded, embedding them would be a better option?
Can we contribute?

In admin login, provide an option to add youtube embed url for a lesson, similar to how the video file is added no.
The embedded link can be loaded as youtube iframe in the lessons next to the downloaded video player.

**Comment by Nikhil13x** [comment]
The embedded link can be loaded as youtube iframe in the lessons next to the downloaded video player.

**Comment by KrzysztofPajak** [comment]
If you need help with some features please send them on our board https://grandnode.com/boards
