### ISSUE TITLE
Grand.Infrastructure.Caching.MemoryCacheExtensions doesn't work on .NET 7

### ISSUE THREAD

**Issue by eerhardt** [grandnode/grandnode2#229]
See the repro steps in https://github.com/dotnet/runtime/issues/63731 for a full analysis of the issue.

In .NET 7, MemoryCache removed its private `EntriesCollection` property. This causes the following code to no longer work:

https://github.com/grandnode/grandnode2/blob/c9f685200a115c86ac230f675fd90ad617814606/src/Core/Grand.Infrastructure/Caching/MemoryCacheExtensions.cs#L12-L15

I'm transferring the dotnet/runtime issue here as the fix will need to be made in Grand.Infrastructure.Caching.MemoryCacheExtensions. MemoryCache can and will change its private implementation details from release to release.

**Comment by KrzysztofPajak** [comment]
@eerhardt 
Thank very much you for the info!
