### ISSUE TITLE
Unable to login at https://demo.grandnode.com/admin

### ISSUE THREAD

**Issue by paragpkulkarni** [grandnode/grandnode2#23]
Unable to login at https://demo.grandnode.com/admin
UserId- admin@yourstore.com
Password- 123456

It is showing error "Login was unsuccessful. Please correct the errors and try again.
No customer account found"

Above credentials are mentioned in README.md

**Comment by PatrykPorabik** [comment]
The demo will be updated after stable release. The Beta version is only for developers to help us during tests.
