### ISSUE TITLE
Cannot get access token

### ISSUE THREAD

**Issue by tonytram** [grandnode/grandnode2#241]
Hi, 

There is a bug in Grand.Api.Validators.Common.LoginValidator, which caused the error below:

_System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters._

Debugging through the code
![image](https://user-images.githubusercontent.com/91330142/156551032-d7f7e02f-9ee8-4925-b297-10da3a1ab9db.png)

At the line 30, it throwed an exception while trying to convert plain text password inputting from user.

**Comment by KrzysztofPajak** [comment]
The problem is related with Base64
