### ISSUE TITLE
ApiAuthenticationRegistrar FrontendAPI config section misspelling

### ISSUE THREAD

**Issue by azieh** [grandnode/grandnode2#249]
Hi there,
after the last update, I faced an error with reading the FrontendAPI config. Misspelling on the name of the config section should be fixed as below.

![image](https://user-images.githubusercontent.com/10528511/160646144-bf5840e0-8b59-4ee5-a3cb-5dfd66a08c40.png)

**Comment by KrzysztofPajak** [comment]
@azieh Thanks, fixed.
