### ISSUE TITLE
Settings-->Catalog --Show specification attr in catalog page -- 

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#252]
![image](https://user-images.githubusercontent.com/10216739/162498024-23ce33a8-10c3-4222-9a25-1904d31fccea.png)

There is no specification attribute showing in category page. 
What is the expected outcome on toggling this flag?

**Comment by KrzysztofPajak** [comment]
Please use our forum to send request: https://grandnode.com/boards
![image](https://user-images.githubusercontent.com/16772986/162501164-efea7224-f211-40b2-8d24-562e35d2e547.png)
