### ISSUE TITLE
Clear cart returns html instead of json

### ISSUE THREAD

**Issue by aristain** [grandnode/grandnode2#258]
Endpoint /cart/clear returns html insted of json when you make an web api call

**Comment by magnuskarlssonhm** [comment]
I get an entire webpage when GET https://localhost:44350/cart as well.

**Comment by magnuskarlssonhm** [comment]
@KrzysztofPajak Out of curiosity, how come fetching a cart and getting a full webpage from an ecom API is not a bug but an enhancement? When would it ever be the expected bahaviour to get a webpage from an API?

**Comment by KrzysztofPajak** [comment]
@magnuskarlssonhm I think you have right, it should be a bug.

**Comment by LeeDalchow** [comment]
Is this ok for me to pick this one up as a first contribution? Already taken a look in the code and found the areas this resides.

Is there a spec for the format of the JSON that is expected? I had a look on this page but it does not detail how the JSON should be formatted & the variable names - https://docs.grandnode.com/operations-on-shopping-cart
