### ISSUE TITLE
Add Segments in Url

### ISSUE THREAD

**Issue by Rezasalami** [grandnode/grandnode2#274]
Hi
i think if we Have Segments in Url it's better For Google Search 
for Example now this url  https://demo.grandnode.com/adidas-turfs 
we redirect to adidas Shoes
but i think better for google this url:  https://demo.grandnode.com/Shoes/adidas-turfs

**Comment by KrzysztofPajak** [comment]
Please use our forum to send request: https://grandnode.com/boards
