### ISSUE TITLE
If we create a product attribute combination, it's not possible to add to cart without selecting the combination, even if the attribute is marked as "Is Required = false".

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#278]
Created 2 attributes for a product and marked as Is Required to false for both of them.
Generated the attribute combinations and set their stock.

When tried to add to cart, the combination works fine. But I am not able to add to cart without selecting at least one combination. 
As the attributes are optional, it should allow to add. Basically, we should be able to add a combination of None x None.

**Comment by KrzysztofPajak** [comment]
Please send your request on our board https://grandnode.com/boards

**Comment by Nikhil13x** [comment]
This is a defect/bug. Board is for suggestions or enhancement i believe...please suggest
