### ISSUE TITLE
bug when importing products

### ISSUE THREAD

**Issue by Ali-HA** [grandnode/grandnode2#28]
null value exception is raised when editing an imported product.
the excel sheet is exported from NopCommerce (4.3). the column **DownloadId** values are zero instead of being blank. GrandNode does not check for imported values. When trying to edit the item a null value exception is raised as the object value for DownloadId does not exist. 
Same for SampleDownloadId
my workaround was to simply clear the 0 values in those columns before importing into GrandNode.

**Comment by PatrykPorabik** [comment]
Well, GrandNode is not nopCommerce, so it's obvious that the excel file exported from nopCommerce, won't work in GrandNode.
