### ISSUE TITLE
In attribute combination, the SKU field is not really linked to the product with same SKU. When price for the SKU is updated, its not reflecting in the attribute combination

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#282]
In attribute combination, the SKU field is not really linked to the product with same SKU. When price for the SKU is updated, its not reflecting in the attribute combination.

Is there a way to associate a product to attribute combination? (the same way as for product attributes)

**Comment by KrzysztofPajak** [comment]
Please send your request on our board https://grandnode.com/boards

**Comment by Nikhil13x** [comment]
This one also is more of a defect.. but can be considered enhancement as there is no association option itself.. will raise in board
