### ISSUE TITLE
Api product Create Automapper

### ISSUE THREAD

**Issue by Row104** [grandnode/grandnode2#286]
Auto mapper does not map any subclasses when creating products via api.

![image](https://user-images.githubusercontent.com/8920335/177572709-940458e0-1f0b-4ace-9bdd-56365b571639.png)

**Comment by KrzysztofPajak** [comment]
It's not a bug.
To insert sub-documents (such as product categories) you can use extra methods

**Comment by Row104** [comment]
how to insert sub doc ProductAttributeCombinations ? There is no endpoint to add attributeCombinations .
