### ISSUE TITLE
Extending category (might be from plugin)

### ISSUE THREAD

**Issue by bouskdav** [grandnode/grandnode2#29]
Hello guys, I would like to extend the category class - more specifically add more images to it. Lets say I want to have some background in breadcrumb (other than title image).

Could you, please, point me in the right way of how to do that?

Thanks, cheers!

**Comment by PatrykPorabik** [comment]
Please ask this question on the community forum - [https://grandnode.com/boards](https://grandnode.com/boards) . GitHub issue tracker is not the right place for that.
