### ISSUE TITLE
Bug in Cart badge icon in Demo Site

### ISSUE THREAD

**Issue by rjs123431** [grandnode/grandnode2#290]
Steps to reproduce:
1. go to product page
2. click Add to cart button - the cart badge changed to 1
3. click Continue on the dialog windows
4. click Add to wishlist button - the wishlist badge changed to 1 but **cart badge changed to 0**

Another scene
1. go to product listing page `/tablets`
2. click Add to cart button of one of the product - the cart badge changed to 1
3. click Quick view of one of the product - **cart badge changed to 0**

**Comment by KrzysztofPajak** [comment]
Thanks, fixed!
