### ISSUE TITLE
Getting server error "The specified Blob already exists". 

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#291]
We have configured to use Azure blobs for the thumbnails. 
But the below error is observed in the checkout page. 
The server should not be shown to client.
![issue](https://user-images.githubusercontent.com/10216739/180823160-f5cf7d8d-afd0-4b3c-ad15-233eeb39feb9.png)

**Comment by Nikhil13x** [comment]
Anyone faced any issues related to thumbnail access.. I faced issues in the mutex implementation as well, when using Azure storage accounts

**Comment by KrzysztofPajak** [comment]
Hello,
On our demo I've use azure blob storage and I can't simulate your issue.
