### ISSUE TITLE
Possibility to hide whole store behind authorization

### ISSUE THREAD

**Issue by bouskdav** [grandnode/grandnode2#298]
Hi,

I thing it would be good to have a possibility to hide whole store behind authentication (e.g. for premium or closed group stores). So far I was able to partially solve it by custom plugin that puts AuthorizeFilter globally, however it makes "not authorized" loop because the login form is also hidden behind this filter.

Would you mind putting an AllowAnonymous attribute to login methods in this repository for these cases? Or could you propose better solution, please?

Regards,
David

**Comment by KrzysztofPajak** [comment]
Hi,
This can be done by AuthorizationFilter
