### ISSUE TITLE
Proper content type missing while uploading image to blob storage causing image rendering issue when used in PDF generation

### ISSUE THREAD

**Issue by SunilParisi123** [grandnode/grandnode2#311]
When we upload image to azure blob storage, content type was not getting set properly. It's getting default to application/octet-stream and this is causing issue when we use these pictures in PDF generation or browse in browser(When we browse URL instead of rendering image it's getting downloaded). Setting up content type for each file helps in rendering the image in browser instead of default download and also rendering in PDF properly.

**Comment by KrzysztofPajak** [comment]
https://github.com/grandnode/grandnode2/pull/312
