### ISSUE TITLE
 Facing some proble to generate new style.min.css file under wwwroot/bundles floder on soluton build. 

### ISSUE THREAD

**Issue by SAISUDHEERREDDY** [grandnode/grandnode2#326]
Hello,

I'm facing some proble to generate new style.min.css file under wwwroot/bundles floder on soluton build. I observed this issue after changing  bundleconfig [bundleconfig.json] structor. how can i find root cause.  due to this issue Im unable to reflect new css changes in production environment. because we are reading style from style.min.css file in the production.

Thank You 

 <environment include="Production">
        @if (supportRtl)
        {
            <link rel="stylesheet" type="text/css" asp-src="/bundles/style.rtl.min.css">
        }
        else
        {
            <link rel="stylesheet" type="text/css" asp-src="/bundles/style.min.css">
        }
    </environment>

**Comment by KrzysztofPajak** [comment]
Hi, 
To build css min you need to run:  npm run build in Grand.Web folder.

**Comment by SAISUDHEERREDDY** [comment]
Hi @KrzysztofPajak,

Thnaks for responting to me. I follow your guidlines but throwing this error "'webpack' is not recognized as an internal or external command". even i runned npm install and npm run build. 
  
Error Screen shot:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/34052545/191933153-6e5a21f0-e59e-4e8b-aa4b-32c0b548e9e2.png">

**Comment by SAISUDHEERREDDY** [comment]
@KrzysztofPajak ,

Its working. i missed installing "npm i -g webpack-cli" 

Thanks for your support.
