### ISSUE TITLE
Add brand name on _CatalogProductView

### ISSUE THREAD

**Issue by Wooody82** [grandnode/grandnode2#329]
Hi
Is it possible to show the brand name under the title on _CatalogProductView.cshtml ?
for example on related product and on category page?

Thanks
<img width="1351" alt="Screenshot 2022-09-25 at 17 20 43" src="https://user-images.githubusercontent.com/9867797/192151367-30fae141-2ae4-4f10-aadf-6b901c954661.png">
<img width="1367" alt="Screenshot 2022-09-25 at 17 20 54" src="https://user-images.githubusercontent.com/9867797/192151368-63635065-7654-43f8-9e8d-ddf127704157.png">

**Comment by KrzysztofPajak** [comment]
@Wooody82 
We do not use github for support, please send your request on our board https://grandnode.com/boards
