### ISSUE TITLE
Categories on homepage

### ISSUE THREAD

**Issue by Wooody82** [grandnode/grandnode2#331]
Is the layout for categories on homepage hardcoded or possible to set it in settings?
Can set the layout for example 4 col or 3 col for categories on homepage or must change the code?

```
@model IList<CategoryModel>
@inject DisplayOrderHomePage order
<div class="categoryGrid  order-@order.HomePageCategories">
    <div cols="12" class="col-12 px-0">
        <div class="form-row">
            @foreach (var item in Model)
            {
                <div class="col-xl-@order.Pc_Xl col-lg-@order.Pc_Lg col-md-@order.Pc_Md col-sm-@order.Pc_Sm col-@order.Pc_Col">
```

That @order.Pc_Xl.. @order.Pc_Lg .. @order.Pc_Md.. comes from DisplayOrderHomePage.cs 
```
using Grand.Domain.Configuration;

namespace Grand.Domain.Common
{
    public class DisplayOrderHomePage : ISettings
    {
        //Home page categories
        public int HomePageCategories { get; set; }
        public int Pc_Xl { get; set; } = 4; //default 4
        public int Pc_Lg { get; set; } = 4; //default 4
        public int Pc_Md { get; set; } = 6; //default 6
        public int Pc_Sm { get; set; } = 6; //default 6
        public int Pc_Col { get; set; } = 12; //default 12
```
        

<img width="1440" alt="Screenshot 2022-09-28 at 17 55 07" src="https://user-images.githubusercontent.com/9867797/192827601-3bec001f-1179-4983-a0cc-80a26da2d97e.png">

**Comment by KrzysztofPajak** [comment]
@Wooody82 
We do not use github for support, please send your request on our board https://grandnode.com/boards
