### ISSUE TITLE
Suspicious code fragments found by PVS-Studio

### ISSUE THREAD

**Issue by VasilievSerg** [grandnode/grandnode2#332]
PVS-Studio (a static analyzer) issued a few warnings on the sources. 
I've described the most suspicious of them below. 

Hope they'll be useful. :)

**Issue 1**
```
public async Task<LessonModel> Handle(GetLesson request, CancellationToken cancellationToken)
{
  var model = new LessonModel();
  var modelCourse = request.Course.ToModel(request.Language);
  
  model.Id = request.Lesson.Id;
  model.CourseId = modelCourse.Id;
  model.CourseDescription = modelCourse.Description;
  model.CourseName = modelCourse.Name;
  model.CourseSeName = modelCourse.SeName;
  model.MetaDescription = modelCourse.MetaDescription;

  model.MetaKeywords = model.MetaKeywords;   // <=
  model.MetaTitle = model.MetaTitle;         // <=     
  ....
}
```
**Link to the sources**: [link](https://github.com/grandnode/grandnode2/blob/c52966143da7cee16534430eba91460642e574c5/src/Web/Grand.Web/Features/Handlers/Courses/GetLessonHandler.cs#L37).

**Warnings**:

- The 'model.MetaKeywords' variable is assigned to itself.
- The 'model.MetaTitle' variable is assigned to itself.

There are two suspicious assignments (they are marked via `// <=`). Perhaps, the right operand should contain the `modelCourse` variable instead of `model`:
```
model.MetaKeywords = modelCourse.MetaKeywords;
model.MetaTitle = modelCourse.MetaTitle;
```
***
**Issue 2**
```
private async Task ReverseBookedInventory(Product product, InventoryJournal inventoryJournal)
{
  ....
  combination.StockQuantity = combination.WarehouseInventory.Sum(x => x.StockQuantity);
  combination.ReservedQuantity = combination.WarehouseInventory.Sum(x => x.StockQuantity); // <=
  product.StockQuantity = product.ProductAttributeCombinations.Sum(x => x.StockQuantity);
  product.ReservedQuantity = product.ProductAttributeCombinations.Sum(x => x.ReservedQuantity);
 ....
}
```
**Link to the sources**: [link](https://github.com/grandnode/grandnode2/blob/c52966143da7cee16534430eba91460642e574c5/src/Business/Grand.Business.Catalog/Services/Products/InventoryManageService.cs#L241).

**Warning**: Two similar code fragments were found. Perhaps, this is a typo and 'ReservedQuantity' variable should be used instead of 'StockQuantity'.

Looks like the `.Sum(x => x.ReservedQuantity)` invocation should be used to calculate the `combination.ReservedQuantity` value. Perhaps, this is a copy-paste error.
***
**Issue 3**
```
private async Task<IList<ContactUsModel.ContactAttributeModel>> PrepareContactAttributeModel(....)
{
 ....
  if (selectedContactAttributes != null || selectedContactAttributes.Any())
    ....
 ....
}
```
**Link to the source**: [link](https://github.com/grandnode/grandnode2/blob/044fc1f21c403ee49b84a6796e07688bf2822665/src/Web/Grand.Web/Commands/Handler/Common/ContactUsSendCommandHandler.cs#L355).

**Warning**: Possible null dereference. Consider inspecting 'selectedContactAttributes'.

The `ArgumentNullException` is possible here. The right operand of the '||' operator will be executed only if `selectedContactAttributes` is `null`. An attempt to call the `Any` method will lead to throwing of the exception. 
***
**Issue 4**

```
public enum SKEncodedImageFormat
{
 ....
  Wbmp = 5,
  Webp = 6,
 ....
}
protected SKEncodedImageFormat EncodedImageFormat(string mimetype)
{
 ....
 if (mimetype.Contains("webp"))
  return SKEncodedImageFormat.Webp;
 if (mimetype.Contains("webp"))
  return SKEncodedImageFormat.Webp;
 ....
}
```
**Link to the sources**: [link](https://github.com/grandnode/grandnode2/blob/044fc1f21c403ee49b84a6796e07688bf2822665/src/Business/Grand.Business.Storage/Services/PictureService.cs#L835).

**Warning**: There are two 'if' statements with identical conditional expressions. The first 'if' statement contains method return. This means that the second 'if' statement is senseless.

The "wepb" format is processed twice while processing of the "webmp" format is missed.

**Comment by KrzysztofPajak** [comment]
@VasilievSerg Thanks for all issue!
