### ISSUE TITLE
Export bug!!!

### ISSUE THREAD

**Issue by NeroLiang19** [grandnode/grandnode2#344]
BUG:

`        public virtual byte[] ExportToByte<T>(PropertyByName<T>[] properties, IEnumerable<T> itemsToExport)
        {
            using var stream = new MemoryStream();
            IWorkbook xlPackage = new XSSFWorkbook();
            ISheet worksheet = xlPackage.CreateSheet(typeof(T).Name);

            //!!! it is necessary !!!
            var manager = new PropertyManager<T>(properties);

            WriteCaption(worksheet, properties);

            var row = 1;

            foreach (var items in itemsToExport)
            {
                WriteToXlsx(properties, worksheet, items, row++);
            }

            xlPackage.Write(stream, false);
            return stream.ToArray();
        }`

**Comment by KrzysztofPajak** [comment]
https://github.com/grandnode/grandnode2/commit/19426e6257636702e1bac9ef07578fb26b29ccb6
