### ISSUE TITLE
HtmlRendererCore.PdfSharp.PdfGenerator is failing.

### ISSUE THREAD

**Issue by eliyasbaby** [grandnode/grandnode2#346]
Getting below exception on submit order, order invoice etc when running on linux environment.

> System.TypeInitializationException: The type initializer for 'HtmlRendererCore.PdfSharp.Adapters.PdfSharpAdapter' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.PlatformNotSupportedException: System.Drawing.Common is not supported on non-Windows platforms. See https://aka.ms/systemdrawingnonwindows for more information. at System.Drawing.LibraryResolver.EnsureRegistered() at System.Drawing.SafeNativeMethods.Gdip.PlatformInitialize() at System.Drawing.SafeNativeMethods.Gdip..cctor() --- End of inner exception stack trace --- at System.Drawing.SafeNativeMethods.Gdip.GdipNewInstalledFontCollection(IntPtr& fontCollection) at HtmlRendererCore.PdfSharp.Adapters.PdfSharpAdapter..ctor() at HtmlRendererCore.PdfSharp.Adapters.PdfSharpAdapter..cctor() --- End of inner exception stack trace --- at HtmlRendererCore.PdfSharp.Adapters.PdfSharpAdapter.get_Instance() at HtmlRendererCore.PdfSharp.HtmlContainer..ctor() at HtmlRendererCore.PdfSharp.PdfGenerator.AddPdfPages(PdfDocument document, String html, PdfGenerateConfig config, CssData cssData, EventHandler`1 stylesheetLoad, EventHandler`1 imageLoad) at HtmlRendererCore.PdfSharp.PdfGenerator.GeneratePdf(String html, PdfGenerateConfig config, CssData cssData, EventHandler`1 stylesheetLoad, EventHandler`1 imageLoad) at Grand.Business.Common.Services.Pdf.HtmlToPdfService.PrintOrdersToPdf(Stream stream, IList`1 orders, String languageId, String vendorId) in /home/runner/work/i_commerce/i_commerce/src/Business/Grand.Business.Common/Services/Pdf/HtmlToPdfService.cs:line 52 at Grand.Business.Common.Services.Pdf.HtmlToPdfService.PrintOrderToPdf(Order order, String languageId, String vendorId) in /home/runner/work/i_commerce/i_commerce/src/Business/Grand.Business.Common/Services/Pdf/HtmlToPdfService.cs:line 78 at Grand.Business.Common.Services.Pdf.HtmlToPdfService.PrintOrderToPdf(Order order, String languageId, String vendorId) in /home/runner/work/i_commerce/i_commerce/src/Business/Grand.Business.Common/Services/Pdf/HtmlToPdfService.cs:line 79 at Grand.Business.Checkout.Commands.Handlers.Orders.ProcessOrderPaidCommandHandler.ProcessOrderPaid(Order order) in /home/runner/work/i_commerce/i_commerce/src/Business/Grand.Business.Checkout/Commands/Handlers/Orders/ProcessOrderPaidCommandHandler.cs:line 61 at Grand.Business.Checkout.Commands.Handlers.Orders.ProcessOrderPaidCommandHandler.Handle(ProcessOrderPaidCommand request, CancellationToken cancellationToken) in /home/runner/work/i_commerce/i_commerce/src/Business/Grand.Business.Checkout/Commands/Handlers/Orders/ProcessOrderPaidCommandHandler.cs:line 40 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken) at Grand.Business.Checkout.Commands.Handlers.Orders.PlaceOrderCommandHandler.Handle(PlaceOrderCommand command, CancellationToken cancellationToken) in /home/runner/work/i_commerce/i_commerce/src/Business/Grand.Business.Checkout/Commands/Handlers/Orders/PlaceOrderCommandHandler.cs:line 200

**Comment by KrzysztofPajak** [comment]
@eliyasbaby Which distribution of linux you are using ?

**Comment by KrzysztofPajak** [comment]
Fixed Use scryber.core pdf engine (https://github.com/grandnode/grandnode2/pull/353)
