### ISSUE TITLE
MongoDB Atlas Raw HTML Save

### ISSUE THREAD

**Issue by mentatpsi** [grandnode/grandnode2#351]
There appears to be issues when saving content such as anything from HomePage text to Bootstrap Sliders with MongoDB Atlas. I'm noticing it doesn't save the content. I don't remember this issue on GrandNode 1.

**Comment by mentatpsi** [comment]
This seems to be mostly happening with raw HTML and not Rich Text

**Comment by KrzysztofPajak** [comment]
@mentatpsi grandnode 1 is no longer supported. In V2 we use summer note, but there is some small issue, after use RAW Html, you need to disable Code View. This issue was reported in summer note.
