### ISSUE TITLE
Bug when we have discount and product attributes

### ISSUE THREAD

**Issue by Wooody82** [grandnode/grandnode2#357]
Hi
I think there is an bug displaying the current price and discount price. 
To reproduce the issue:
1. Create new discount for ex with 25% for brand or products 
2. Create a product with normal price and then create a product attributes with multi ones

The product will show the same prices on actual price and discount price.

Not sure what exactly the issue, But I have tested to change the class **price-value-@(Model.ProductId)** and it fix the issue.. line 55:
    `            <span class="price-value-@(Model.ProductId) @if (string.IsNullOrEmpty(Model.PriceWithDiscount)) {<text>actual-price</text>}">`

And seems its same issue on line: 94 . it does not render the **<strong class="actual-price">@Html.Raw(Model.PriceWithDiscount)</strong>** ... instead it render the same span with the class only.
`<span class="your-price price-value-@(Model.ProductId)">`

<img width="403" alt="Screenshot 2023-01-11 at 00 23 27" src="https://user-images.githubusercontent.com/9867797/211683410-a4f91335-63d8-4e3b-8ee9-b4fdb9260f54.png">

**Comment by NeroLiang19** [comment]
There are still bug，when we have discount and product attributes。
Discount type:
![image](https://user-images.githubusercontent.com/24262475/213103291-beae7f8a-e329-4302-950b-0696ccaf31ce.png)

no product attributes is right.

**Comment by NeroLiang19** [comment]
Hello,
Still Bug! When we have discount and product attributes.
I already pull the latest version(master branch).

No product attributes is right!
![1674025226297_3705EFD8-3D03-40fe-8549-D14D024708A9](https://user-images.githubusercontent.com/24262475/213106506-9abd77b2-4ad5-449a-8ccf-bf117223bb21.png)

But When we have discount and product attributes:
![image](https://user-images.githubusercontent.com/24262475/213107041-79add305-e000-489f-bd4c-a6e58f499dbc.png)

expect price is:

**Comment by KrzysztofPajak** [comment]
Please check this link: https://grandnode.azurewebsites.net/adidas-predator-instinct
There is a discount 10 USD and you have product with attributes

**Comment by KrzysztofPajak** [comment]
and Shopping cart looks like this:
![image](https://user-images.githubusercontent.com/16772986/213527376-4b143556-dd4e-420f-a0d1-b2deb1b772e3.png)

**Comment by NeroLiang19** [comment]
Hi KrzysztofPajak,

Thanks for your answer.

 **The link : https://grandnode.azurewebsites.net/adidas-predator-instinct  is right,because the price is fixed at 149, but different skus of my products have different prices, so I overriden the price. when I have discount(types: assigned for products) and product attributes. By the way the fixed price is 555** 
![image](https://user-images.githubusercontent.com/24262475/215252521-08e3d3d8-4187-4071-9ed2-ad499196a85a.png)
![image](https://user-images.githubusercontent.com/24262475/215252560-2ebc6e81-84d5-4338-a805-077ba335568d.png)
