### ISSUE TITLE
Extending Order (or any other) base entity

### ISSUE THREAD

**Issue by bouskdav** [grandnode/grandnode2#359]
Hey guys,

just want to know if you have any recommended way of extending base entities? In my particular case it's InvoiceNumber and InvoiceEffectiveDate fields.

One way I think about is creating another entity (like OrderInvoiceExtension) and just make a relation through OrderGuid / OrderNumber.

What do you think?

Thanks,
David

**Comment by KrzysztofPajak** [comment]
@bouskdav I would like to suggest to use UserFields.

**Comment by bouskdav** [comment]
OK, and is there a way to get UserField value casted to a type or one is limited to .ToString() and .Parse or Convert.To... ? Thanks by the way.

**Comment by bouskdav** [comment]
Thanks ) looks good
