### ISSUE TITLE
How to create specification attributes

### ISSUE THREAD

**Issue by Macka323** [grandnode/grandnode2#360]
Hello, 
I am trying to create a specification attribute, but the way i think they work is, you create an attribute and then the product either has that attribute or it doest.
But i want to create attribute with value, ex computers have 4gb, 8gb, 16gb ram etc. and i want to use those specification atributes to filter products in category. 
Thanks

**Comment by KrzysztofPajak** [comment]
Please send your request to https://grandnode.com/boards
