### ISSUE TITLE
Error loading tier prices table when the customer group is deleted which was mapped to a tier price entry

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#363]
1. Create a tier price using a customer group 'A'
2. Now delete the customer group 'A'
3. After this, the tier price table doesn't load as there is null reference exception in the ProductVIewModelService logic,

Should the fix be done by adding a null check or by using a EntityDeleted handler on CustomerGroup delete,  to scan through all the products and remove the corresponding tier prices?

**Comment by KrzysztofPajak** [comment]
Thanks, fixed

**Comment by Nikhil13x** [comment]
Thanks for the fix.
