### ISSUE TITLE
Google analytics upgrade to GA4 is required

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#371]
Google Analytics 4 is replacing Universal Analytics. On July 1, 2023 all standard Universal Analytics properties will stop processing new hits. 360 Universal Analytics properties will stop processing new hits on July 1, 2024. [Learn more](https://support.google.com/analytics/answer/11583528)

If you have a Universal Analytics property, you must migrate. [Check if you have a Universal Analytics property](https://support.google.com/analytics/answer/11583832). The earlier you migrate, the more historical data and insights you will have in Google Analytics 4.

https://support.google.com/analytics/answer/10759417?hl=en

Any plans for this in roadmap?

**Comment by KrzysztofPajak** [comment]
@Nikhil13x Yes, we have plan upgrade it, in grandnode version 2.10

**Comment by Nikhil13x** [comment]
Thanks.
@KrzysztofPajak  Do you have any planned timeline? Or any link to see the roadmap features.
