### ISSUE TITLE
Default Store Language is incorrect

### ISSUE THREAD

**Issue by Macka323** [grandnode/grandnode2#372]
When you visit the site, the default store language, is incorrect (in my case it goes to English) instead of the chosen one.
![image](https://user-images.githubusercontent.com/75259519/221015690-4ed65828-a0f2-499b-a312-99ac0b8ca2bb.png)

**Comment by KrzysztofPajak** [comment]
@Macka323 Please check in the incognito browser mode.

**Comment by Macka323** [comment]
@KrzysztofPajak I have checked in incognito mode, cleared cookies and on another device, and it doesn't change the language

**Comment by KrzysztofPajak** [comment]
@Macka323 
Go to admin: Settings -> System settings:
check options: Automatically detect the current language by a customer region (from browser settings)

**Comment by Macka323** [comment]
@KrzysztofPajak 
I have checked, and its turned on

**Comment by KrzysztofPajak** [comment]
@Macka323 Language settings -> Automatically Detect Language has more power then Default Language on the store. It's by design

**Comment by Macka323** [comment]
Umm, where can i find that setting? I cant seem to find it.

**Comment by KrzysztofPajak** [comment]
@Macka323 sorry for confusing: Language settings -> Automatically Detect Language = Settings -> System settings Automatically detect the current language by a customer region
