### ISSUE TITLE
Pre-order Product Order Filter Functionality

### ISSUE THREAD

**Issue by purnadika** [grandnode/grandnode2#385]
Currently there is Pre-order function. But somehow the back end doesn't have any way to check if sales order has pre-order in it. Therefore, admin would never know if the sales order has pre-order product in it.

Expected behavior

Any identification of orders that has pre-order product in it. Along with Pre-order availability date both in admin page and exported excel.
May also better with Pre-order report that tells all both active and old pre-order orders

**Comment by KrzysztofPajak** [comment]
@purnadika You can use order tags features. Every order can be tagged, in the admin panel you can filtering orders by tag.

**Comment by purnadika** [comment]
@KrzysztofPajak I think that's only effective if you have only few orders.
Might be disaster for thousands orders.

**Comment by KrzysztofPajak** [comment]
You can write your own handler to update tag on the order.
