### ISSUE TITLE
I think it's time to upgrade to .NET 7 :) 

### ISSUE THREAD

**Issue by ravichigurupalli** [grandnode/grandnode2#390]
with .NET 7...It's entirely native, with no IL or JIT, and provides fast startup time and a small, self-contained deployment.
I am interested to contribute, Please accept my request.

**Comment by KrzysztofPajak** [comment]
@ravichigurupalli Thanks, but we waiting for version net core 8.0

**Comment by ravichigurupalli** [comment]
@KrzysztofPajak  Thanks for the response, Do you want me to close this ticket?
