### ISSUE TITLE
Bundle product not loaded when selecting the associated category

### ISSUE THREAD

**Issue by fabiorme** [grandnode/grandnode2#391]
bundled products are not loaded when selecting the associated category.
if instead they are searched in the search bar they are displayed.

example:
https://www.iltuoprodotto.it/quartetto-routine-caduta-e-assottigliamento-genesis-homme-kerastase

the product is visible but if you select its associated category it does not appear.... 
https://www.iltuoprodotto.it/trattamento-per-cute

how can it be displayed?

I installed the version GrandNode 2 - 1.1.1

Thank you

**Comment by KrzysztofPajak** [comment]
Please send your question on our board https://grandnode.com/boards
