### ISSUE TITLE
Wrong icon of grid view in Catalog/_Selectors.cshtml patial (when string "Grid" gets localized)

### ISSUE THREAD

**Issue by bouskdav** [grandnode/grandnode2#40]
Line 57 in : /Views/Catalog/_Selectors.cshtml

`<template v-if="viewmode.Text == 'Grid'">`

depends on string 'Grid' which can be translated, so I would propose to change it to:

`<template v-if="viewmode.Value.includes('viewmode=grid')">`

**Comment by dan269** [comment]
@bouskdav, thanks in advance
