### ISSUE TITLE
Add Cart Button is not working Properly

### ISSUE THREAD

**Issue by keshavashourie** [grandnode/grandnode2#407]
Hi Everyone,I was checking the Demo URL ( https://demo.grandnode.com/smartwatches#) i saw list of watches and tried to add some watches to the Cart , but when i click **Add to Cart** Button Sometimes it works as expected and sometimes it will move to product description Page.

For example consider the Watch **"Garmin VivoActive"** from the above mentioned link and click Add to Cart button here instead of adding the product to cart it moves to Product Description Page.

**Comment by KrzysztofPajak** [comment]
@keshavashourie Everything works as expected. When product has any attributes then you are redirect to the product page. When product does not have any attributes then product is added to the cart.
If you need help please use this board: https://grandnode.com/boards
