### ISSUE TITLE
Update to .NET 8

### ISSUE THREAD

**Issue by KrzysztofPajak** [grandnode/grandnode2#428]

**Comment by phanvancan** [comment]
Help Me!

 - Click to link Admin Error 

An unhandled exception occurred while processing the request.
InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Areas/Admin/Views/Home/Index.en-US.cshtml
/Areas/Admin/Views/Home/Index.en.cshtml
/Areas/Admin/Views/Home/Index.cshtml
/Areas/Admin/Views/Shared/Index.en-US.cshtml
/Areas/Admin/Views/Shared/Index.en.cshtml
/Areas/Admin/Views/Shared/Index.cshtml
/Views/Shared/Index.en-US.cshtml
/Views/Shared/Index.en.cshtml
/Views/Shared/Index.cshtml
Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable<string> originalLocations)

Stack Query Cookies Headers Routing
InvalidOperationException: The view 'Index' was not found. The following locations were searched: /Areas/Admin/Views/Home/Index.en-US.cshtml /Areas/Admin/Views/Home/Index.en.cshtml /Areas/Admin/Views/Home/Index.cshtml /Areas/Admin/Views/Shared/Index.en-US.cshtml /Areas/Admin/Views/Shared/Index.en.cshtml /Areas/Admin/Views/Shared/Index.cshtml /Views/Shared/Index.en-US.cshtml /Views/Shared/Index.en.cshtml /Views/Shared/Index.cshtml
Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable<string> originalLocations)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
Grand.Web.Common.Middleware.ContextLoggingMiddleware.InvokeAsync(HttpContext context) in ContextLoggingMiddleware.cs
+
        await _next(context);
Grand.Web.Common.Middleware.CultureSettingMiddleware.InvokeAsync(HttpContext context, IWorkContext workContext) in CultureSettingMiddleware.cs
+
        await _next(context);
Grand.Web.Common.Middleware.WorkContextMiddleware.InvokeAsync(HttpContext context, IWorkContextSetter workContext) in WorkContextMiddleware.cs
+
        await _next(context);
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

**Comment by s3group** [comment]
still getting error for 2.2.2.1 I have using .net  SDK 8.0.101
