### ISSUE TITLE
Proposal: add new StyleTagHelper to allow inserting <style> block to header from components

### ISSUE THREAD

**Issue by bouskdav** [grandnode/grandnode2#43]
Hi,

I would propose to add new StyleTagHelper to allow inserting <style> block to header from inside components or wherever `@section head { ... }` is unavailable.

One can then use it from e.g. component as:

```
<style asp-location="Header">
    @Html.Raw(Model.AdditionalCss)
</style>
```

Let me know, I can send PR.

Cheers,
David

**Comment by KrzysztofPajak** [comment]
Hi @bouskdav 
Sure, go ahead

Regards
Krzysztof

**Comment by bouskdav** [comment]
PR sent. Cheers!
