### ISSUE TITLE
Shipping Status filter in Orders page is not filtering in some cases

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#445]
![image](https://github.com/grandnode/grandnode2/assets/10216739/7be02310-9439-4ca0-a9ee-9942c46c84a1)

The filter is not filtering for "Shipping Not Required" , as the enum value for this option is is 0 and considered as "All" in the logic.

![image](https://github.com/grandnode/grandnode2/assets/10216739/4a7bf97b-9003-4de3-98d1-886771f3fe78)

**Comment by KrzysztofPajak** [comment]
@Nikhil13x please check
