### ISSUE TITLE
While Checking out with any product for a specific country the state field is empty

### ISSUE THREAD

**Issue by zak1123456** [grandnode/grandnode2#454]
![Screenshot 2024-01-03 105806](https://github.com/grandnode/grandnode2/assets/144582236/907cda1d-f0b3-4b89-8ec2-8471a2ae0aa5)

**Comment by KrzysztofPajak** [comment]
@zak1123456 Please report any inquiries such as product support to our forum, which is available here https://grandnode.com/boards
