### ISSUE TITLE
Setup failed: Method ToLowerInvariant() in String are not supported when convert to BsonExpression 

### ISSUE THREAD

**Issue by rualb** [grandnode/grandnode2#479]
## Issue
Setup failed: Method ToLowerInvariant() in String are not supported when convert to BsonExpression 
(value(Grand.Business.Customers.Services.CustomerService+<>c__DisplayClass11_0).email.ToLowerInvariant()).

## Temp Solution
replacing from .ToLowerInvariant to .ToLower on using with .email and .username 

## Note
setup to LiteDB  (vers 5.0.19)

**Comment by KrzysztofPajak** [comment]
The problem is in LiteDb, I've send PR on LiteDb https://github.com/mbdavid/LiteDB/pull/2468

**Comment by KrzysztofPajak** [comment]
@rualb please check
