### ISSUE TITLE
RTL languages - The display order of "Left time" is incorrect in auction products

### ISSUE THREAD

**Issue by pourali1982** [grandnode/grandnode2#48]
The display order of "Left time" is incorrect in auction products  for rtl languages.
see this image please:
![err](https://user-images.githubusercontent.com/86197661/123540681-7a5c6680-d755-11eb-85c9-44fea54d4715.jpg)

**Comment by pourali1982** [comment]
And in "contact us", after submit a message, the result isn't rtl:
![err](https://user-images.githubusercontent.com/86197661/123748003-e6131080-d8c8-11eb-9af9-26e6ac485185.jpg)

**Comment by pourali1982** [comment]
another issue related to RTL mode: 
![err](https://user-images.githubusercontent.com/86197661/123946425-724e3200-d9b4-11eb-970e-08c97ac0f315.jpg)

Also the name of writer (Guest) is not friendly (see the image)

**Comment by pourali1982** [comment]
> The display order of "Left time" is incorrect in auction products for rtl languages.
> see this image please:
> ![err](https://user-images.githubusercontent.com/86197661/123540681-7a5c6680-d755-11eb-85c9-44fea54d4715.jpg)

This issue is not fixed in new release

**Comment by pourali1982** [comment]
> And in "contact us", after submit a message, the result isn't rtl:
> ![err](https://user-images.githubusercontent.com/86197661/123748003-e6131080-d8c8-11eb-9af9-26e6ac485185.jpg)

This issue is not fixed in new release

**Comment by pourali1982** [comment]
> another issue related to RTL mode:
> ![err](https://user-images.githubusercontent.com/86197661/123946425-724e3200-d9b4-11eb-970e-08c97ac0f315.jpg)
> 
> Also the name of writer (Guest) is not user friendly (see the image)

This issue is not fixed in new release except "Customer.Guest"

**Comment by pourali1982** [comment]
> And in "contact us", after submit a message, the result isn't rtl:
> ![err](https://user-images.githubusercontent.com/86197661/123748003-e6131080-d8c8-11eb-9af9-26e6ac485185.jpg)

،This issue not solved in new release.

**Comment by pourali1982** [comment]
> The display order of "Left time" is incorrect in auction products for rtl languages.
> see this image please:
> ![err](https://user-images.githubusercontent.com/86197661/123540681-7a5c6680-d755-11eb-85c9-44fea54d4715.jpg)

Suggested code:

`    <span class="col-form-label">@Loc["AddToCart.Timeleft"]: </span>
	if (supportRtl)
    {
        <span>{{ `${timeObj.s}` }} : </span>
        <span>{{ `${timeObj.m}` }} : </span>
        <span>{{ `${timeObj.h}` }} : </span>
        <span>{{ `${timeObj.d}` }}</span>
    }
    else
    {
        <span>{{ `${timeObj.d}` }} : </span>
        <span>{{ `${timeObj.h}` }} : </span>
        <span>{{ `${timeObj.m}` }} : </span>
        <span>{{ `${timeObj.s}` }} : </span>
    }`

**Comment by PatrykPorabik** [comment]
@dan269 can you look at this?
