### ISSUE TITLE
The Activity Log feature is missing in the latest release. 

### ISSUE THREAD

**Issue by Nikhil13x** [grandnode/grandnode2#486]
In the previous versions, we used to have a user activity log at customer level as well as product level. 
This used to provide a level of Audit on any edit/delete actions- "Who What When" 
Is there any alternate provided for auditing currently

**Comment by KrzysztofPajak** [comment]
@Nikhil13x In the application, we use a standard logging provider. In appsettings, you can set the log level for each controller. When you integrate with Application Insights, you will receive a lot of information
