### ISSUE TITLE
discount requirement 'subtotal in shopping cart x.xx' is actually 'customer had spent x.xx amount'

### ISSUE THREAD

**Issue by kjames2001** [grandnode/grandnode2#488]
discount requirement 'subtotal in shopping cart x.xx' is actually 'customer had spent x.xx amount'.

it even shows 'Required spent amount' when choosing the 'subtotal in shopping cart x.xx' rule.
![图片](https://github.com/grandnode/grandnode2/assets/62420081/35cd698d-6afb-437b-9565-1b11f97165e5)

**Comment by KrzysztofPajak** [comment]
@kjames2001 I've just checked, and I think it works as it should. When you use the discount rule: "Customer has spent x.xx amount," your customer must have at least one complete order with an amount greater than X. Then, for the next order, the discount will be applied.

**Comment by kjames2001** [comment]
> @kjames2001 I've just checked, and I think it works as it should. When you use the discount rule: "Customer has spent x.xx amount," your customer must have at least one complete order with an amount greater than X. Then, for the next order, the discount will be applied.

I'm actually trying to use 'subtotal in shopping cart x.xx', but it doesn't work.
