### ISSUE TITLE
Build fails with .NET SDK 8.0.400

### ISSUE THREAD

**Issue by LangleJ** [grandnode/grandnode2#508]
Visual studio 17.11.4 puts us on .NET SDK 8.0.400. 

global.json permits this with "rollForward": "latestFeature"

The build fails with these errors:
48>HEAD
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1093,22,1093,68): error CS0101: The namespace '<global namespace>' already contains a definition for '__Generated__AdminWidgetViewComponentTagHelper'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(736,13,736,18): error CS8802: Only one compilation unit can have top-level statements.
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(736,13,736,18): error CS8802: Only one compilation unit can have top-level statements.
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\Areas\Admin\Views\_ViewImports.cshtml(59,20,59,23): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1074,87,1074,110): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1078,60,1078,63): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1082,70,1082,79): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1086,71,1086,75): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1090,83,1090,87): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\Areas\Admin\Views\_ViewImports.cshtml(59,20,59,23): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1074,87,1074,110): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1078,60,1078,63): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1082,70,1082,79): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1086,71,1086,75): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1090,88,1090,92): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\Areas\Admin\Views\_ViewImports.cshtml(59,9,59,19): error CS0246: The type or namespace name 'LocService' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\Areas\Admin\Views\_ViewImports.cshtml(59,9,59,19): error CS0246: The type or namespace name 'LocService' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1090,71,1090,81): error CS0246: The type or namespace name 'BrandModel' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1090,71,1090,86): error CS0246: The type or namespace name 'CollectionModel' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\Areas\Admin\Views\_ViewImports.cshtml(59,20,59,23): error CS0102: The type '<invalid-global-code>' already contains a definition for 'Loc'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1074,87,1074,110): error CS0102: The type '<invalid-global-code>' already contains a definition for 'ModelExpressionProvider'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1078,60,1078,63): error CS0102: The type '<invalid-global-code>' already contains a definition for 'Url'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1082,70,1082,79): error CS0102: The type '<invalid-global-code>' already contains a definition for 'Component'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1086,71,1086,75): error CS0102: The type '<invalid-global-code>' already contains a definition for 'Json'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1090,88,1090,92): error CS0102: The type '<invalid-global-code>' already contains a definition for 'Html'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1096,20,1096,66): error CS0111: Type '__Generated__AdminWidgetViewComponentTagHelper' already defines a member called '__Generated__AdminWidgetViewComponentTagHelper' with the same parameter types
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1104,71,1104,83): error CS0111: Type '__Generated__AdminWidgetViewComponentTagHelper' already defines a member called 'ProcessAsync' with the same parameter types
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(1111,48,1111,70): error CS0111: Type '__Generated__AdminWidgetViewComponentTagHelper' already defines a member called 'ProcessInvokeAsyncArgs' with the same parameter types
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(716,13,716,41): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(716,13,716,41): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(716,13,716,41): error CS0501: '<invalid-global-code>.<invalid-global-code>()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(717,13,717,25): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(717,13,717,25): error CS0501: '<invalid-global-code>.<invalid-global-code>()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(718,44,718,70): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(718,44,718,70): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(718,44,718,70): error CS0501: '<invalid-global-code>.<invalid-global-code>()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,19,731,36): error CS0246: The type or namespace name '__tagHelperRunner' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,51,734,72): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,23,734,50): error CS0246: The type or namespace name '__tagHelperExecutionContext' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(716,13,716,41): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(716,13,716,41): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(716,13,716,41): error CS0501: '<invalid-global-code>.<invalid-global-code>()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(717,13,717,25): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(717,13,717,25): error CS0501: '<invalid-global-code>.<invalid-global-code>()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(718,44,718,70): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(718,44,718,70): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(718,44,718,70): error CS0501: '<invalid-global-code>.<invalid-global-code>()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,19,731,36): error CS0246: The type or namespace name '__tagHelperRunner' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,51,734,72): error CS0116: A namespace cannot directly contain members such as fields, methods or statements
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,23,734,50): error CS0246: The type or namespace name '__tagHelperExecutionContext' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(710,13,710,25): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(710,13,710,25): error CS0501: 'Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo.Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(711,232,711,237): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(346,113,346,159): error CS0426: The type name '__Generated__AdminWidgetViewComponentTagHelper' does not exist in the type 'Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo'
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,46,731,73): error CS0246: The type or namespace name '__tagHelperExecutionContext' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,13,731,18): error CS0246: The type or namespace name 'await' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,19,731,36): error CS0538: '__tagHelperRunner' in explicit interface declaration is not an interface
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,37,731,45): error CS0501: '<invalid-global-code>.RunAsync(__tagHelperExecutionContext)' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,46,731,73): error CS0246: The type or namespace name '__tagHelperExecutionContext' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,13,731,18): error CS0246: The type or namespace name 'await' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,19,731,36): error CS0538: '__tagHelperRunner' in explicit interface declaration is not an interface
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,37,731,45): error CS0501: '<invalid-global-code>.RunAsync(__tagHelperExecutionContext)' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,17,734,22): error CS0246: The type or namespace name 'await' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,23,734,50): error CS0538: '__tagHelperExecutionContext' in explicit interface declaration is not an interface
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,51,734,72): error CS0501: '<invalid-global-code>.SetOutputContentAsync()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,17,734,22): error CS0246: The type or namespace name 'await' could not be found (are you missing a using directive or an assembly reference?)
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,23,734,50): error CS0538: '__tagHelperExecutionContext' in explicit interface declaration is not an interface
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,51,734,72): error CS0501: '<invalid-global-code>.SetOutputContentAsync()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(731,37,731,45): error CS0111: Type '<invalid-global-code>' already defines a member called '__tagHelperRunner.RunAsync' with the same parameter types
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Collection_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(734,51,734,72): error CS0111: Type '<invalid-global-code>' already defines a member called '__tagHelperExecutionContext.SetOutputContentAsync' with the same parameter types
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(710,13,710,25): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(710,13,710,25): error CS0501: 'Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo.Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo()' must declare a body because it is not marked abstract, extern, or partial
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(711,232,711,237): error CS1520: Method must have a return type
37>H:\grandnode2_2.21\src\Web\Grand.Web.Admin\obj\Debug\net8.0\Microsoft.CodeAnalysis.Razor.Compiler\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo_cshtml.g.cs(346,108,346,154): error CS0426: The type name '__Generated__AdminWidgetViewComponentTagHelper' does not exist in the type 'Areas_Admin_Views_Brand_Partials_CreateOrUpdate_TabSeo'
37>Done building project "Grand.Web.Admin.csproj" -- FAILED.

Installing .NET SDK 8.0.101 manually and modifying global.json to "rollForward": "disable" fixes it.

**Comment by eliyasbaby** [comment]
I am also getting the same razor compilation issue. I think its due to the naming of admin tag helpers in the Grand.Web.Common project.

**Comment by LangleJ** [comment]
> Installing .NET SDK 8.0.101 manually and modifying global.json to "rollForward": "disable" fixes it.

Installing .NET SDK 8.0.101 manually and modifying global.json to "rollForward": "disable" fixes it.

**Comment by KrzysztofPajak** [comment]
@LangleJ On my environment after install net sdk-8.0.400 I do not have any issue. Please try to use latest version of sdk.

**Comment by rolan18** [comment]
@LangleJ @eliyasbaby I was able to get the project to run on the version @KrzysztofPajak mentioned.
I just had to update the dotnet cmd on my machine.
I believe the command was something like `dotnet workload update`.
