### ISSUE TITLE
Documentation for shipping module

### ISSUE THREAD

**Issue by gadonski** [grandnode/grandnode2#53]
Hello, i wanna write a new plugin for Correios (postal service in Brazil), where´s the documentation? I wanna calc the shipping value on cart page before checkout. How to do it?

**Comment by PatrykPorabik** [comment]
Hello @gadonski , please wait a few days for developers' docs. We will release them after publishing a stable version of GrandNode 2.0.

**Comment by gadonski** [comment]
thanks @PatrykPorabik
