### ISSUE TITLE
Could not load type: 'MongoDB.Driver.Linq.IMongoQueryable' from assembly: 'MongoDB.Driver, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94992a53043e321'.

### ISSUE THREAD

**Issue by daithanhpc** [grandnode/grandnode2#537]
I got an error on brand Master commit at  "Commits on Dec 2, 2024".

I call api load all project with url "https://localhost:44350/odata/product" via post main.

Could not load type: 'MongoDB.Driver.Linq.IMongoQueryable' from assembly: 'MongoDB.Driver, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94992a53043e321'.

![image](https://github.com/user-attachments/assets/3840310f-a061-4989-831a-5d856cf8f462)

**Comment by KrzysztofPajak** [comment]
@daithanhpc problem is related with https://github.com/mongodb/mongo-aspnetcore-odata
We have to wait for the new release of this nuget.

**Comment by Sen-Gupta** [comment]
Even after updating to new version 3.1.0.0, the issue still persists

'Could not load type 'MongoDB.Driver.Linq.IMongoQueryable' from assembly 'MongoDB.Driver, Version=3.1.0.0, Culture=neutral, PublicKeyToken=94992a530f44e321'.'

**Comment by Sen-Gupta** [comment]
After a little more digging, I find the following.

It is a breaking change being introduced in MongoDB 3.0
[https://www.mongodb.com/docs/drivers/csharp/v3.0/upgrade/v3/](https://www.mongodb.com/docs/drivers/csharp/v3.0/upgrade/v3/)

The driver replaces the IMongoQueryable interface with the IQueryable interface, following the pattern used by most other LINQ providers. If your application contains references to IMongoQueryable, replace them with IQueryable.

We need to change the code as suggested.

**Comment by Sen-Gupta** [comment]
And the only change required is to change(Quick Search/Replace did the trick for me)

Attribute MongoEnableQuery to EnableQuery.
<img width="529" alt="image" src="https://github.com/user-attachments/assets/d3d97c50-3042-461f-bcaf-a4c8493826b4">


I built and tested. Let me know if you accept a pull request.

I have tested the API end points after this and it works as expected.

**Comment by KrzysztofPajak** [comment]
@Sen-Gupta, MongoEnableQuery allows you to use full query options, such as Select, and others. Let's wait a few days for the NuGet package. If a new version doesn't appear, I'll copy the code from the repository and update the type.

**Comment by KrzysztofPajak** [comment]
@Sen-Gupta fixed
