### ISSUE TITLE
Missing localisation for 'Filters' button

### ISSUE THREAD

**Issue by vadim-danilchik** [grandnode/grandnode2#54]
Line 82 in 
https://www.github.com/grandnode/grandnode2/tree/master/src%2FWeb%2FGrand.Web.Admin%2FAreas%2FAdmin%2FViews%2FOrder%2FList.cshtml

**Comment by PatrykPorabik** [comment]
You're right. Thanks for the notification, I will make a fix in a moment.

**Comment by PatrykPorabik** [comment]
Done
