### ISSUE TITLE
Unable to Run the latest Main Branch

### ISSUE THREAD

**Issue by Sen-Gupta** [grandnode/grandnode2#545]
Steps to Re-produce!

Clone Main Branch!

Build and Run! 

You will run into the following:

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5021/page-not-found - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5021/page-not-found - 302 0 - 1.8296ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5021/install - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5021/install - 302 0 - 1.7875ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET https://localhost:5021/install, Response status code: 302
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5021/page-not-found - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5021/page-not-found - 302 0 - 1.7546ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5021/install - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5021/install - 302 0 - 1.9214ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[16]
      Request reached the end of the middleware pipeline without being handled by application code. Request path: GET https://localhost:5021/install, Response status code: 302
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5021/page-not-found - - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5021/page-not-found - 302 0 - 1.7239ms

I'm not sure if it because of some cookies at my end.

Reproduce with Existing instance:

Clone latest main Branch:

Observe in console (Run using Kestrel)

      Adding to ApplicationParts: 'Payments.StripeCheckout'
fail: PluginManager[0]
      RegisterPluginInterface
      System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
      Could not load file or assembly 'Stripe.net, Version=47.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      Could not load file or assembly 'Stripe.net, Version=47.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
         at System.Reflection.RuntimeModule.GetDefinedTypes()
         at System.Reflection.RuntimeModule.GetTypes()
         at Grand.Infrastructure.Plugins.PluginManager.RegisterPluginInterface(IMvcCoreBuilder mvcCoreBuilder, Assembly assembly) in D:\RNDRepo\grandnode2\src\Core\Grand.Infrastructure\Plugins\PluginManager.cs:line 368
      System.IO.FileNotFoundException: Could not load file or assembly 'Stripe.net, Version=47.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'Stripe.net, Version=47.2.0.0, Culture=neutral, PublicKeyToken=null'
      System.IO.FileNotFoundException: Could not load file or assembly 'Stripe.net, Version=47.2.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
      File name: 'Stripe.net, Version=47.2.0.0, Culture=neutral, PublicKeyToken=null'

**Comment by Sen-Gupta** [comment]
I believe, We need to update the:

    <PackageVersion Include="Stripe.net" Version="47.2.0" />

and fix the build copy from net8.0 to net9.0

<Target Name="CopyFile" AfterTargets="AfterBuild">
    <ItemGroup>
        <CopyFiles Include="$(NuGetPackageRoot)\stripe.net\47.2.0\lib\net9.0\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(CopyFiles)" DestinationFolder="..\..\Web\Grand.Web\Plugins\Payments.StripeCheckout\" />
</Target>

**Comment by KrzysztofPajak** [comment]
@Sen-Gupta currently we use <PackageVersion Include="Stripe.net" Version="47.1.0" />
The issue is in your changes

**Comment by Sen-Gupta** [comment]
@KrzysztofPajak , deleting the old obj folders manually fixed it.
Thanks

**Comment by Sen-Gupta** [comment]
Documenting it here to save some time while you upgrade it later.

The real issue turned out that while all other dependencies live in net9.0 folder, the upgraded stripe.net 47.2.0 still lives in .net 8.0 folder under nuget installation.
` <CopyFiles Include="$(NuGetPackageRoot)\stripe.net\47.2.0\lib\net8.0\*.dll" />` [Correct configuration]
In result, during plugins folder creation this will be never copied as I had it moved it to 47.2.0\lib\net9.0\*.dll [Incorrect configuration].

Great work @KrzysztofPajak.

**Comment by little-fish-foundation** [comment]
the same error
