### ISSUE TITLE
Unable to resolve service for type 'Grand.Infrastructure.IWorkContext' while attempting to activate 'Widgets.Slider.Services.SliderService'.

### ISSUE THREAD

**Issue by Sen-Gupta** [grandnode/grandnode2#553]
Latest dev branch seems to have refactored and perhaps still in work-in-progress/

An unhandled exception occurred while processing the request.
InvalidOperationException: Unable to resolve service for type 'Grand.Infrastructure.IWorkContext' while attempting to activate 'Widgets.Slider.Services.SliderService'.
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, bool throwIfCallSiteNotFound)

**Comment by KrzysztofPajak** [comment]
@Sen-Gupta I would like to suggest rebuild all plugins after download latest version

**Comment by Sen-Gupta** [comment]
@KrzysztofPajak, deleting, plugins/modules/obj folder under Grand.Web did the trick.

Thanks
