### ISSUE TITLE
Orders cannot delete in Admin/Order/List page

### ISSUE THREAD

**Issue by pourali1982** [grandnode/grandnode2#56]
I login with admin account,
In Admin/Order/List, I try to delete an order but I cant
In Admin/Order/Edit I can
Is it a bug?

**Comment by PatrykPorabik** [comment]
Well, I checked this and on our test environment, the most recent one, everything works fine. Can you confirm that you have the newest version? Maybe check the System -> Log, for more info. Or f12 chrome console for JS logs?

**Comment by KrzysztofPajak** [comment]
Thanks, but this issue was fixed: https://github.com/grandnode/grandnode2/commit/c0c104312f3b509eb54c63d8486575d7954a3ad7

**Comment by pourali1982** [comment]
> Well, I checked this and on our test environment, the most recent one, everything works fine. Can you confirm that you have the newest version? Maybe check the System -> Log, for more info. Or f12 chrome console for JS logs?

U right. I didnt know release 1 is published

**Comment by pourali1982** [comment]
> Thanks, but this issue was fixed: [c0c1043](https://github.com/grandnode/grandnode2/commit/c0c104312f3b509eb54c63d8486575d7954a3ad7)

This issue is not fixed in new release.
