### ISSUE TITLE
new realse error

### ISSUE THREAD

**Issue by hexroot007** [grandnode/grandnode2#57]
after installing the new  today realse there is a error in chrome 
![eee](https://user-images.githubusercontent.com/12569168/124615213-7d123680-de8e-11eb-9e7a-a190bf3a906c.PNG)
console

**Comment by PatrykPorabik** [comment]
Well, press the ctrl + f5 in your browser. It should work.

**Comment by hexroot007** [comment]
its worked :) but after deployment it will show error or not let me see cheers

**Comment by KrzysztofPajak** [comment]
Hi @hexroot007 
Please clear your browser cache.
