### ISSUE TITLE
Marks not localized

### ISSUE THREAD

**Issue by pourali1982** [grandnode/grandnode2#63]
Marks - "New" , "Promo" - not localized (resource string)
If you dont mind, It's my pleasure to start contribution with this issue

![err](https://user-images.githubusercontent.com/86197661/124999631-cff11700-e063-11eb-9855-52ba8676d5cf.jpg)

**Comment by PatrykPorabik** [comment]
Hello! @pourali1982 . Thanks a lot for your involvement. But in that case, it's a custom field on a category. So it's not a resource string :) 
![image](https://user-images.githubusercontent.com/16773025/125121565-666d1900-e0f4-11eb-8932-2b8460a72a69.png)

**Comment by pourali1982** [comment]
OMG
Thanks :D

**Comment by pourali1982** [comment]
> Hello! @pourali1982 . Thanks a lot for your involvement. But in that case, it's a custom field on a category. So it's not a resource string :)
> ![image](https://user-images.githubusercontent.com/16773025/125121565-666d1900-e0f4-11eb-8932-2b8460a72a69.png)

OMG
Thanks :D

**Comment by pourali1982** [comment]
> Hello! @pourali1982 . Thanks a lot for your involvement. But in that case, it's a custom field on a category. So it's not a resource string :)
> ![image](https://user-images.githubusercontent.com/16773025/125121565-666d1900-e0f4-11eb-8932-2b8460a72a69.png)

Flag in category is localized but "Flag" in product detail is not
