### ISSUE TITLE
Link for digital ocean deployment on Readme.md still pointing to Old version of Grannode

### ISSUE THREAD

**Issue by paragpkulkarni** [grandnode/grandnode2#77]
Following is a link for the digital ocean on Readme.md which is an old version Grandnode
https://marketplace.digitalocean.com/apps/grandnode?refcode=8eafb78fb6ae

Also, Grandnode2 is not searchable in the digital ocean marketplace. The marketplace is still showing the old version of Grandnode

**Comment by KrzysztofPajak** [comment]
Your issue is not related with the code of grandnode. Please use our [board ](https://grandnode.com/boards) to send us a question.
