### ISSUE TITLE
Add new address form doesn't hide when you select the "Pickup" checkbox

### ISSUE THREAD

**Issue by vadim-danilchik** [grandnode/grandnode2#78]
New address form still shown If you select "new address" in dropdown and then click "Pickup"
![image](https://user-images.githubusercontent.com/45650122/126788683-5728a39f-8b12-4b17-8676-498e645d3b85.png)

Using "value" can fixed it
`if (!document.querySelector("#shipping-address-select").value)`

https://github.com/grandnode/grandnode2/blob/0e529d923cb11074b699ca18ae6f06f493db79b7/src/Web/Grand.Web/wwwroot/theme/script/public.checkout.js#L309

https://github.com/grandnode/grandnode2/blob/0e529d923cb11074b699ca18ae6f06f493db79b7/src/Web/Grand.Web/wwwroot/theme/script/public.checkout.js#L320

**Comment by KrzysztofPajak** [comment]
Could you reproduce on our demo https://demo.grandnode.com/

**Comment by vadim-danilchik** [comment]
> Could you reproduce on our demo https://demo.grandnode.com/
It is reproduced if you have saved address
![image](https://user-images.githubusercontent.com/45650122/126816591-7b200cb5-661d-4ca5-bb6f-541f69c6a0b0.png)

**Comment by PatrykPorabik** [comment]
Hello @vadim-danilchik , thanks a lot for reporting, we will fix it shortly.
