### ISSUE TITLE
_adminMenuProviders.ToList() return nothing

### ISSUE THREAD

**Issue by pourali1982** [grandnode/grandnode2#80]
"src\Web\Grand.Web.Admin\Areas\Admin\Views\Shared\Menu.cshtml" Line 29 "_adminMenuProviders.ToList()" returns nothing

In my plugin, my Provider class (CashOnVendorAccountPaymentProvider) inherits IPaymentProvider and IAdminMenuProvider

This is my code but it doesnt work:

`
        public Task ManageSiteMap(SiteMapNode rootNode)
        {
            var pluginNode = rootNode.ChildNodes.FirstOrDefault(x => x.SystemName == "Accounting");
            if (pluginNode == null)
            {
                rootNode.ChildNodes.Add(new SiteMapNode() {
                    SystemName = "Accounting",
                    Visible = true,
                    IconClass = "icon-puzzle",
                    ResourceName = "Plugins.Payment.CashOnVendorAccount.MSN.AccountingMenuTitle"
                });
                pluginNode = rootNode.ChildNodes.FirstOrDefault(x => x.SystemName == "Accounting");
            }
            var Menu = new SiteMapNode();
            Menu.ResourceName = "Plugins.Payment.CashOnVendorAccount.MSN.Accounting.VendorAccounts";
            Menu.Visible = true;
            Menu.SystemName = "Accounting.VendorAccounts";
            if (pluginNode != null)
            {
                pluginNode.ChildNodes.Add(Menu);
            }
            else
            {
                rootNode.ChildNodes.Add(Menu);
            }
            return Task.CompletedTask;
        }

`

**Comment by KrzysztofPajak** [comment]
@pourali1982 I would like to suggest that every provider should have a separate class. Then you can register it, below you can find the sample code. 
```
public class StartupApplication : IStartupApplication
    {
        public void ConfigureServices(IServiceCollection services, IConfiguration configuration)
        {
            services.AddScoped<IAdminMenuProvider, MyAdminMenu>();
        }

        public void Configure(IApplicationBuilder application, IWebHostEnvironment webHostEnvironment)
        {

        }

        public int Priority => 0;

        public bool BeforeConfigure => false;
    }
```

**Comment by pourali1982** [comment]
Thanks a lot
