### ISSUE TITLE
Recurring payments

### ISSUE THREAD

**Issue by bmiki** [grandnode/grandnode2#82]
Do you plan to implement recurring payment support? I would like to move my site from nopcommerce 4.4 to grandnode2, but my payment plugin is using recurring payment support that is not implemented in grandnode2.

**Comment by PatrykPorabik** [comment]
Hi there,

There is recurring payment support, but it's done totally different than in nopCommerce. As we have Payment transactions, recurring order means that your system creates a new payment transaction document inside single subscription order. You don't have to create dozen of orders for a subscription. If you want, you can reach us at support@grandnode.com we will help you with your migration process and with designing a new workflow of actions.
