### ISSUE TITLE
Azure deployment - getting error while configuring mangodb

### ISSUE THREAD

**Issue by balajivelu147** [grandnode/grandnode2#84]
![image](https://user-images.githubusercontent.com/34922609/128062913-d0151d9e-7bcb-474c-8fe8-4b91b61d3a43.png)
![image](https://user-images.githubusercontent.com/34922609/128064619-b509814c-4802-4337-a895-183a2f74df9b.png)

when I tried with localhost its working fine and its creating DB as  expected, but the same connection string is not working in azure app service version... tried all possible ways...

**Comment by PatrykPorabik** [comment]
@balajivelu147 timeout error means that you provided the wrong connection string, in that case, you should check it and correct. We didn't notice any problems during the installation on Azure.

**Comment by balajivelu147** [comment]
mongodb+srv://balajimc22:<password>@cluster0.vqhyk.mongodb.net/tonearme?authSource=admin 

this is the connection string i used in local to connect remote mongodb and it worked, but in azure version its failing

**Comment by balajivelu147** [comment]
mongodb+srv://balajimc22:<password>@cluster0.vqhyk.mongodb.net/tonearme?authSource=admin 

this is the connection string i used in local to connect remote mongodb and it worked, but in azure version its failing
