### ISSUE TITLE
Orders operations via the API

### ISSUE THREAD

**Issue by AhmadGadallahMostafa** [grandnode/grandnode2#85]
Hello, I was wondering if there are requests available that enable working with orders via the API as I did not find in the documentation [here](https://docs.grandnode.com/web-api)

**Comment by PatrykPorabik** [comment]
Hello @AhmadGadallahMostafa 

Sure, there are available requests that enable working with orders via the API. You can purchase the Extended Web API plugin to enable them. [https://grandnode.com/extended-web-api](https://grandnode.com/extended-web-api)
