### ISSUE TITLE
Please load Frame first and Products later

### ISSUE THREAD

**Issue by Rajat37** [grandnode/grandnode2#88]
Please load Frame first and Products later on scroll instead of page number. It will increase page load time. No matter how much products we will added on home page.
![IMG_20210808_105620](https://user-images.githubusercontent.com/47422681/128621860-8b3980c6-a816-44c4-8e8c-f1731a900a67.jpg)
Like this
![IMG_20210808_104859](https://user-images.githubusercontent.com/47422681/128621867-a5547d2b-7fca-4cd9-b68c-9d151c9b0beb.jpg)

**Comment by PatrykPorabik** [comment]
Thanks a lot for suggestion.
