### ISSUE TITLE
pdf generating issue at customer tab orders print orders and orders tab admin panel

### ISSUE THREAD

**Issue by hexroot007** [grandnode/grandnode2#94]
wkhtmltopdf error exit with code 1 due to network error: hostnotfounderror.

**Comment by PatrykPorabik** [comment]
It's the error coming from whktmltopdf and I suppose it's related to your VM host.

**Comment by hexroot007** [comment]
i am running it on local machine right now.

**Comment by PatrykPorabik** [comment]
Host not found error clearly shows that there is a problem with the used host. It has nothing to do with the app. According to the forum post, where you noted that you have a problem with disappearing plugins, I assume that there is a problem with your environment.
